apiVersion: v1
kind: Service
metadata:
  name: candy-shop-service
  labels:
    app: candy-shop
spec:
  selector:
    app: candy-shop
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 
  type: LoadBalancer
